In [48]:
import numpy as np

In [49]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
array1.ravel(order='F')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
array2 = array1.reshape(5, 6)
array2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [54]:
#2.呈上題的array，找出被6除餘1的數的索引
array3 = np.where((array2 % 6) == 1)
array3

(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))

In [52]:
np.where((array2 % 6) == 1, "Y", "N") 

array([['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'Y', 'N', 'N', 'N', 'N']], dtype='<U1')

In [55]:
for i in array3:
    print(i)

[0 1 2 3 4]
[1 1 1 1 1]
