In [221]:
import numpy as np

In [222]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [223]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [224]:
a = np.mean(english_score)
b = np.nanmean(math_score)
c = np.mean(chinese_score)
score_mean = np.array((a,b,c))
score_mean

array([67.16666667, 66.6       , 75.33333333])

In [225]:
d = np.amax(english_score)
e = np.nanmax(math_score)
f = np.amax(chinese_score)
score_max = np.array((d,e,f))
score_max

array([89., 85., 90.])

In [226]:
g = np.amin(english_score)
h = np.nanmin(math_score)
i = np.amin(chinese_score)
score_min = np.array((g,h,i))
score_min

array([48., 60., 65.])

In [227]:
j = np.std(english_score)
k = np.nanstd(math_score)
l = np.std(chinese_score)
score_std = np.array((j,k,l))
score_std

array([13.43399502,  9.70772888,  8.8254682 ])

In [228]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [229]:
math_score_makeup = np.array([60,85,60,68,55,60])
m = np.mean(english_score)
n = np.mean(math_score_makeup)
o = np.mean(chinese_score)
score_mean_makeup = np.array((m,n,o))
score_mean_makeup

array([67.16666667, 64.66666667, 75.33333333])

In [230]:
p = np.amax(english_score)
q = np.max(math_score_makeup)
r = np.amax(chinese_score)
score_max_makeup = np.array((p,q,r))
score_max_makeup

array([89, 85, 90])

In [231]:
s = np.amin(english_score)
t = np.nanmin(math_score_makeup)
u = np.amin(chinese_score)
score_min_makeup = np.array((s,t,u))
score_min_makeup

array([48, 55, 65])

In [232]:
v = np.std(english_score)
w = np.nanstd(math_score_makeup)
x = np.std(chinese_score)
score_std_makeup = np.array((v,w,x))
score_std_makeup

array([13.43399502,  9.86013297,  8.8254682 ])

In [233]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [234]:
y = np.corrcoef(english_score,chinese_score)
z = np.corrcoef(math_score_makeup,chinese_score)
score_corrcoef = np.array((y,z))
score_corrcoef
#與國文成績相關係數最高的學科是英文

array([[[1.        , 0.97792828],
        [0.97792828, 1.        ]],

       [[1.        , 0.74056803],
        [0.74056803, 1.        ]]])