In [32]:
import numpy as np
array1 = np.array([[10, 8], [3, 5]])
array1

array([[10,  8],
       [ 3,  5]])

In [33]:
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array2 = np.linalg.inv(array1)
array2

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [34]:
array3 = array1@array2
array3

array([[1., 0.],
       [0., 1.]])

In [35]:
#運用上列array計算特徵值、特徵向量
w, v = np.linalg.eig(array3)
w

array([1., 1.])

In [36]:
v

array([[1., 0.],
       [0., 1.]])

In [37]:
#運用上列array計算SVD?
u, s, vh = np.linalg.svd(array3)

In [ ]:
u